### ISSUE TITLE
협회 확인건

### ISSUE THREAD

**Issue by songseulgi** [hmparki253/Voucher#1]
만족도 조사, 약관동의 언제까지 넘겨줄 수 있는지 확인필요.

**Comment by hmparki253** [comment]
#test

**Comment by hmparki253** [comment]
## 만족도조사, 약관동의
7월 12일까지 전달의사 확인 완료 (유선상으로)

**Comment by songseulgi** [comment]
만족도 조사 , 약관동의 받음.(2016-07-12)
