### ISSUE TITLE
멘토 기초경영역량보고서 작성권한 오류

### ISSUE THREAD

**Issue by songseulgi** [hmparki253/Voucher#16]
A 기업이 C BA에게 다수의 컨설팅을 받는경우, C BA의 멘토는 1명일 때 BA가 멘토를 컨설팅 코드와 함께 기업을 매칭할 때 멘토의 기초경영역량 보고서 작성권한이 Y에서 N,N...으로 바뀜. => 기초경영역량 보고서 작성권한 없어짐.

**Comment by OhYoonLee** [comment]
해당 기업과 멘토를 조회하여 WRITE_YN="Y"가 하나라도 있으면 작성 권한이 Y로 되게 수정
